version: '3.8'

networks:
  vpn-sea:
    driver: bridge

volumes:
  data-volume:
  seareport:
    name: drive-seareport
  mariadb-data:
    name: mariadb-data

services:

  db:
    image: 'mariadb:latest'
    command: --default-authentication-plugin=mysql_native_password --general_log=ON --bind_address=0.0.0.0
    restart: always
    environment:
      MARIADB_DATABASE: seareport
      MARIADB_USER: seareport_user
      MARIADB_PASSWORD: seareport_password
      MARIADB_ROOT_PASSWORD: root
      MARIADB_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - "mariadb-data:/var/lib/mysql"
    networks:
      - vpn-sea

  seareport-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: seareport:latest
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/seareport
      SPRING_DATASOURCE_USERNAME: seareport_user
      SPRING_DATASOURCE_PASSWORD: seareport_password
    volumes:
      - data-volume:/app/data
    networks:
      - vpn-sea
    healthcheck:
      test: ["CMD", "curl", "-f", "http://db:3306"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

