spring:
  datasource:
    url: ${DB_DESENV_URL}?createDatabaseIfNotExist=true
    username: ${DB_DESENV_USERNAME}
    password: ${DB_DESENV_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update