spring:
  datasource:
    url: jdbc:mariadb://${DB_DESENV_SERVER:localhost}:${DB_DESENV_PORT:3306}/${DB_DESENV_NAME:SeaReport}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect
