spring:
  datasource:
    url: ${DB_HOMOLOG_URL}
    username: ${DB_HOMOLOG_USERNAME}
    password: ${DB_HOMOLOG_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.Oracle12cDialect